const playList = [

"https://jetsetradio.live/radio/stations/lofi/Nymano - Women.mp3",
"https://jetsetradio.live/radio/stations/lofi/Omar - Serene.mp3",
"https://jetsetradio.live/radio/stations/lofi/Omarr - Chai.mp3",
"https://jetsetradio.live/radio/stations/lofi/Omarr - Good Morning.mp3",
"https://jetsetradio.live/radio/stations/lofi/Pandrezz - by the bridge at night (feat. nohone).mp3",
"https://jetsetradio.live/radio/stations/lofi/Pheeno - Rest.mp3",
"https://jetsetradio.live/radio/stations/lofi/Porou - Sweet Dreams Love.mp3",
"https://jetsetradio.live/radio/stations/lofi/Potsu - CHAM.mp3",
"https://jetsetradio.live/radio/stations/lofi/Potsu - losing sight.mp3",
"https://jetsetradio.live/radio/stations/lofi/Potsu - Oops.mp3",
"https://jetsetradio.live/radio/stations/lofi/Prima - June Gloom.mp3",
"https://jetsetradio.live/radio/stations/lofi/Probe - Stardust Walkway (Sonic Lofi).mp3",
"https://jetsetradio.live/radio/stations/lofi/Redpest - Sleepy Time Beats.mp3",
"https://jetsetradio.live/radio/stations/lofi/Rook1e - I Fell In Love With You One Night In September.mp3",
"https://jetsetradio.live/radio/stations/lofi/RUDE - Eternal Youth.mp3",
"https://jetsetradio.live/radio/stations/lofi/sad boy with a laptop - evergreen.mp3",
"https://jetsetradio.live/radio/stations/lofi/Sad Boy With A Laptop - I Was Lost Until I Met You.mp3",
"https://jetsetradio.live/radio/stations/lofi/Sad Boy With A Laptop - Portals To Mystical Worlds.mp3",
"https://jetsetradio.live/radio/stations/lofi/sad boy with a laptop - you were so far away.mp3",
"https://jetsetradio.live/radio/stations/lofi/Saik - Wet Season.mp3",
"https://jetsetradio.live/radio/stations/lofi/Saiko - Sofia Drift.mp3",
"https://jetsetradio.live/radio/stations/lofi/Sarcastic Sounds - I Don't Sleep.mp3",
"https://jetsetradio.live/radio/stations/lofi/Sarcastic Sounds & Ezra - Thinking Of You.mp3",
"https://jetsetradio.live/radio/stations/lofi/Satin - Unknown.mp3",
"https://jetsetradio.live/radio/stations/lofi/Sinh - Poetry (Feat Natty Reeves).mp3",
"https://jetsetradio.live/radio/stations/lofi/Sleepdealer - Naturals.mp3",
"https://jetsetradio.live/radio/stations/lofi/slipfunc - a spring without you.mp3",
"https://jetsetradio.live/radio/stations/lofi/smuv - looped.mp3",
"https://jetsetradio.live/radio/stations/lofi/Sonic Lofi - Green Chill Zone.mp3",
"https://jetsetradio.live/radio/stations/lofi/Sonic Lofi - Low Spec Robo Go.mp3",
"https://jetsetradio.live/radio/stations/lofi/Splatoon 2 Octo Expansion - 8-Ball LoFi Hip Hop Remix.mp3",
"https://jetsetradio.live/radio/stations/lofi/Super Mario World - Game Over LoFi Hip Hop Remix.mp3",
"https://jetsetradio.live/radio/stations/lofi/SURF - Instant Brew.mp3",
"https://jetsetradio.live/radio/stations/lofi/SURF - Take Care.mp3",
"https://jetsetradio.live/radio/stations/lofi/THAIBEATS - Faithful.mp3",
];

export default playList;